package proyectotransversal.Vistas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectotransversal.AccesoAData.AlumnoData;
import proyectotransversal.AccesoAData.InscripcionData;
import proyectotransversal.AccesoAData.MateriaData;
import proyectotransversal.Entidades.Alumno;
import proyectotransversal.Entidades.Inscripcion;
import proyectotransversal.Entidades.Materia;

public class ManejoInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloInscriptos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private DefaultTableModel modeloNoInscriptos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    InscripcionData inscripcionData = new InscripcionData();
    AlumnoData alumnoData = new AlumnoData();
    MateriaData materiaData = new MateriaData();

    /**
     * Creates new form ManejoInscripcion
     */
    public ManejoInscripcion() {
        initComponents();
        crearTabla();
        cargarcombobox();
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNoInscripto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInscripto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBaja = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Inscripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 1326, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 1326, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 1326, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Seleccionar Alumno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jcbAlumnos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbAlumnos.setBorder(null);
        jcbAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAlumnosItemStateChanged(evt);
            }
        });
        jcbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 410, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 1326, 10));

        jTableNoInscripto.setBackground(new java.awt.Color(208, 204, 204));
        jTableNoInscripto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableNoInscripto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNoInscripto.getTableHeader().setReorderingAllowed(false);
        jTableNoInscripto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableNoInscriptoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNoInscripto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 410, 80));

        jTableInscripto.setBackground(new java.awt.Color(208, 204, 204));
        jTableInscripto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableInscripto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableInscripto.getTableHeader().setReorderingAllowed(false);
        jTableInscripto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableInscriptoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableInscripto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 410, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Materias a las que estas Inscripto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 220, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Materias a las que no estas Inscripto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 240, -1));

        jButtonBaja.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/playlist_remove_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButtonBaja.setText("Darse de baja");
        jButtonBaja.setBorder(null);
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 155, 30));

        jButtonAlta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/playlist_add_check_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButtonAlta.setText("Darse de alta");
        jButtonAlta.setBorder(null);
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 160, 30));

        jButtonSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSalir.setText("Atras");
        jButtonSalir.setBorder(null);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 100, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 544, 1326, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jcbAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAlumnosItemStateChanged
        actualizar();
    }//GEN-LAST:event_jcbAlumnosItemStateChanged

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        baja();
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        alta();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jTableNoInscriptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableNoInscriptoKeyPressed
        // TODO add your handling code here:
        /*
        jTableNoInscripto.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    alta();
                }
            }
        });*/
        
    }//GEN-LAST:event_jTableNoInscriptoKeyPressed

    private void jTableInscriptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableInscriptoKeyPressed
        // TODO add your handling code here:
        /*
        jTableInscripto.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    baja();
                }
            }
        });*/
    }//GEN-LAST:event_jTableInscriptoKeyPressed

    private void jcbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableInscripto;
    private javax.swing.JTable jTableNoInscripto;
    private javax.swing.JComboBox<Alumno> jcbAlumnos;
    // End of variables declaration//GEN-END:variables
private void crearTabla() {
        modeloInscriptos.addColumn("ID");
        modeloInscriptos.addColumn("Año de cursada");
        modeloInscriptos.addColumn("Nombre de la Materia");

        modeloNoInscriptos.addColumn("ID");
        modeloNoInscriptos.addColumn("Año de cursada");
        modeloNoInscriptos.addColumn("Nombre de la Materia");

        jTableInscripto.setModel(modeloInscriptos);
        jTableNoInscripto.setModel(modeloNoInscriptos);

        jTableInscripto.setEnabled(true);
        jTableNoInscripto.setEnabled(true);

        jTableInscripto.setRowSelectionAllowed(true);
        jTableNoInscripto.setRowSelectionAllowed(true);

    }

    private void cargarTabla() {
        Alumno aux = (Alumno) jcbAlumnos.getSelectedItem();
        int id = aux.getIdAlumno();

        if (inscripcionData.obtenerMateriasCursadas(id) != null) {
            for (Materia materia : inscripcionData.obtenerMateriasCursadas(id)) {
                modeloInscriptos.addRow(new Object[]{materia.getIdMateria(), materia.getAñoMateria(), materia.getNombre()});
            }
        } else {
            System.out.println("No hay datos en el array");
        }

        if (inscripcionData.obtenerMateriasNOCursadas(id) != null) {
            for (Materia materia : inscripcionData.obtenerMateriasNOCursadas(id)) {
                modeloNoInscriptos.addRow(new Object[]{materia.getIdMateria(), materia.getAñoMateria(), materia.getNombre()});
            }
        } else {
            System.out.println("No hay datos en el array");
        }

    }

    private void cargarcombobox() {
        for (Alumno alumno : alumnoData.listarAlumnos()) {
            jcbAlumnos.addItem(alumno);
        }
    }

    private void borrarfila() {
        int f = jTableInscripto.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloInscriptos.removeRow(f);
        }
        int f2 = jTableNoInscripto.getRowCount() - 1;
        for (; f2 >= 0; f2--) {
            modeloNoInscriptos.removeRow(f2);
        }
    }

    private void actualizar() {
        borrarfila();
        cargarTabla();
    }
    private void baja(){
        int filas = jTableInscripto.getSelectedRow();
        if (filas != -1) {
            int idMateria = (int) jTableInscripto.getValueAt(filas, 0);
            Alumno aux = (Alumno) jcbAlumnos.getSelectedItem();
            int idAlumno = aux.getIdAlumno();
            inscripcionData.borrarInscripcionMateriaAlumno(idAlumno, idMateria);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
        actualizar();
    }
    private void alta(){
        int filas = jTableNoInscripto.getSelectedRow();
        if (filas != -1) {
            int idMateria = (int) jTableNoInscripto.getValueAt(filas, 0);
            Alumno aux = (Alumno) jcbAlumnos.getSelectedItem();
            int idAlumno = aux.getIdAlumno();

            Alumno alumno = alumnoData.buscarAlumno(idAlumno);
            Materia materia = materiaData.buscarmateria(idMateria);

            Inscripcion inscripcion = new Inscripcion(0, alumno, materia, 0);
            inscripcionData.guardarinscripcion(inscripcion);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
        actualizar();
    }
}
