/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectotransversal.Vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectotransversal.AccesoAData.AlumnoData;
import proyectotransversal.AccesoAData.InscripcionData;
import proyectotransversal.AccesoAData.MateriaData;
import proyectotransversal.Entidades.Alumno;
import proyectotransversal.Entidades.Inscripcion;
import proyectotransversal.Entidades.Materia;

/**
 *
 * @author crist
 */
public class ManejoInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloInscriptos = new DefaultTableModel();
    private DefaultTableModel modeloNoInscriptos = new DefaultTableModel();
    InscripcionData inscripcionData = new InscripcionData();
    AlumnoData alumnoData = new AlumnoData();
    MateriaData materiaData = new MateriaData();

    /**
     * Creates new form ManejoInscripcion
     */
    public ManejoInscripcion() {
        initComponents();
        crearTabla();
        cargarcombobox();
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNoInscripto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInscripto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBaja = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Seleccionar Alumno:");

        jcbAlumnos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcbAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAlumnosItemStateChanged(evt);
            }
        });

        jTableNoInscripto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNoInscripto);

        jTableInscripto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableInscripto);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Materias a las que estas Inscripto");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Materias a las que no estas Inscripto");

        jButtonBaja.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonBaja.setText("Darse de Baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonAlta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAlta.setText("Darse de Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonSalir.setText("Atras");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addGap(75, 75, 75)
                        .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333)
                        .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBaja)
                    .addComponent(jButtonAlta))
                .addGap(8, 8, 8)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jcbAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAlumnosItemStateChanged
        actualizar();
    }//GEN-LAST:event_jcbAlumnosItemStateChanged

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        int filas = jTableInscripto.getSelectedRow();
        if (filas!=-1){
            int id = (int) jTableInscripto.getValueAt(filas,1);
            inscripcionData.eliminarinscripcion(id);
        }else{  
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }
        actualizar();
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        int filas = jTableInscripto.getSelectedRow();
        if (filas!=-1){
            int idMateria = (int) jTableInscripto.getValueAt(filas,1);
            int anio = (int) jTableInscripto.getValueAt(filas,2);
            String nombre = (String) jTableInscripto.getValueAt(filas,3);
            
            Alumno aux = (Alumno) jcbAlumnos.getSelectedItem();
            int idAlumno = aux.getIdAlumno();
            
            Alumno alumno = alumnoData.buscarAlumno(idAlumno);
            Materia materia = materiaData.buscarmateria(idMateria);
            
            Inscripcion inscripcion = new Inscripcion(0,alumno,materia,0);
            inscripcionData.guardarinscripcion(inscripcion);
        }else{  
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }
        actualizar();
    }//GEN-LAST:event_jButtonAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableInscripto;
    private javax.swing.JTable jTableNoInscripto;
    private javax.swing.JComboBox<Alumno> jcbAlumnos;
    // End of variables declaration//GEN-END:variables
private void crearTabla() {
        modeloInscriptos.addColumn("ID");
        modeloInscriptos.addColumn("Año de cursada");
        modeloInscriptos.addColumn("Nombre de la Materia");

        modeloNoInscriptos.addColumn("ID");
        modeloNoInscriptos.addColumn("Año de cursada");
        modeloNoInscriptos.addColumn("Nombre de la Materia");

        jTableInscripto.setModel(modeloInscriptos);
        jTableNoInscripto.setModel(modeloNoInscriptos);

        jTableInscripto.setEnabled(false);
        jTableNoInscripto.setEnabled(false);

        jTableInscripto.setRowSelectionAllowed(true);
        jTableNoInscripto.setRowSelectionAllowed(true);

    }

    private void cargarTabla() {
        InscripcionData inscripcionData = new InscripcionData();
        Alumno aux = (Alumno) jcbAlumnos.getSelectedItem();
        int id = aux.getIdAlumno();

        if (inscripcionData.obtenerMateriasCursadas(id) != null) {
            for (Materia materia : inscripcionData.obtenerMateriasCursadas(id)) {
                modeloInscriptos.addRow(new Object[]{materia.getIdMateria(), materia.getAnioMateria(), materia.getNombre()});
            }
        } else {
            System.out.println("No hay datos en el array");
        }

        if (inscripcionData.obtenerMateriasNOCursadas(id) != null) {
            for (Materia materia : inscripcionData.obtenerMateriasNOCursadas(id)) {
                modeloNoInscriptos.addRow(new Object[]{materia.getIdMateria(), materia.getAnioMateria(), materia.getNombre()});
            }
        } else {
            System.out.println("No hay datos en el array");
        }

    }

    private void cargarcombobox() {
        for (Alumno alumno : alumnoData.listarAlumnos()) {
            jcbAlumnos.addItem(alumno);
        }

    }

    private void borrarfila() {
        int f = jTableInscripto.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloInscriptos.removeRow(f);
        }
         int f2 = jTableNoInscripto.getRowCount() - 1;
        for (; f2 >= 0; f2--) {
            modeloNoInscriptos.removeRow(f2);
        }
    }
    private void actualizar(){
        borrarfila();
        cargarTabla();
    }
}
